### ISSUE TITLE
Android: renderer not initialized

### ISSUE THREAD

**Issue by giacomoran** [amake/flutter_tex_js#7]
On Android I'm getting the following error when I add a `TexImage` widget:

```
E/AndroidRuntime(14339): FATAL EXCEPTION: DefaultDispatcher-worker-1
E/AndroidRuntime(14339): Process: com.example.latex_test, PID: 14339
E/AndroidRuntime(14339): kotlin.UninitializedPropertyAccessException: lateinit property renderer has not been initialized
E/AndroidRuntime(14339): 	at com.madlonkay.flutter_tex_js.FlutterTexJsPlugin.access$getRenderer$p(FlutterTexJsPlugin.kt:16)
E/AndroidRuntime(14339): 	at com.madlonkay.flutter_tex_js.FlutterTexJsPlugin$handleRender$1.invokeSuspend(FlutterTexJsPlugin.kt:99)
E/AndroidRuntime(14339): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(14339): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/AndroidRuntime(14339): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
E/AndroidRuntime(14339): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
E/AndroidRuntime(14339): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
```

It reproduced in a couple sample apps.

It seems like `onAttachedToEngine` is getting called. I've tried to debug the issue but could get anywhere.

Happy to provide more information or test more if needed.

**Comment by amake** [comment]
Thanks for the report. I was able to reproduce simply by

1. Create sample project with `flutter create -t app sample_app`
2. Add `flutter_tex_js: ^1.2.1` to dependencies
3. Add a `TexImage` widget with arbitrary content

**Comment by amake** [comment]
It looks like it has something to do with the version of Kotlin your app is using.

The default Kotlin version for a new app generated by `flutter create` is 1.3.50. With this version I get the error you reported.

If you update your app's Kotlin version to something newer, like 1.4.32, then it works.

(My production app is on 1.4.32 so I never noticed this issue.)

I will try to resolve the incompatibility, but it's possible that a newer Kotlin will simply become a requirement for this plugin (in which case I will document it properly).

**Comment by amake** [comment]
Kotlin 1.3.60 is the oldest version I can find that seems to work. I poked through the [changelog](https://github.com/JetBrains/kotlin/blob/master/docs/changelogs/ChangeLog-1.3.X.md#1360) but I have not found any hints as to what changed that might be relevant.

**Comment by amake** [comment]
This issue doesn't seem to occur in a Flutter app that uses Java instead of Kotlin, presumably because the plugin pulls in its preferred version of Kotlin.

But it might be possible for an app that depends on multiple Kotlin-using plugins to have Kotlin resolve to a problematic version.

**Comment by amake** [comment]
I think this issue should be moot now as Flutter defaults to a new-enough version of Kotlin.

https://github.com/flutter/flutter/blob/c792a1721cd38b90bed56b536879516cf6b59aab/packages/flutter_tools/lib/src/android/gradle_utils.dart#L33

The requirement is also now documented.
